---
# apache 2 license
# install exist-db on a system that does not yet have exist-db installed
# because the data folder is embeded in the exist instance folder it
# is NOT possible to upgrade exist-db using this playbook
#
# ------------------------------------
# ------- USE AT YOUR OWN RISK -------
# ------------------------------------
#
# TODO list
#    parameterize
#    break into modules that can be included
#    add inet.d startup
#    change sudoer file
#    sudoer changes
#    change port to 80 or make firewall change
#    memory settings
#    WHAT ELSE?
#
- hosts: naked-existdb
  vars:
    existSvnUrl: svn://svn.code.sf.net/p/exist/code/stable/eXist-2.0.x
    existDir: /usr/local/exist2.0.x
    existLn: /usr/local/exist
    java_home: /usr/lib/jvm/java
    buildSucess: x
  user: ec2-user
  sudo: yes


  tasks:
  - name: find out of build of exist has already been successful
    action: shell cat ${existDir}/buildExist.log | grep "BUILD SUCCESSFUL"
    ignore_errors: True
    register: buildSuccess
   
  
  - name: test the register variable
    debug: msg="'${buildSuccess.stdout}'.find("1") is the stdout message"

# this works leave this here till be make use this code elsewhere
  - name: test
    debug: msg="test is successful"
    when_string: ${buildSuccess.stdout} != 'BUILD SUCCESSFUL'
      
  - name: install java-1.7.0-openjdk latest version
    action: yum pkg=java-1.7.0-openjdk state=latest
    
  - name: set alternatives up for java 1.7 openJdk
    action: script ../../bash/javaAlternatives.sh
    
  - name: install ant lastest version
    action: yum pkg=ant state=latest
    when_string: ${buildSuccess.stdout} != 'BUILD SUCCESSFUL'
    
  - name: install svn
    action: yum pkg=svn state=present
    when_string: ${buildSuccess.stdout} != 'BUILD SUCCESSFUL'
    
  - name: checkout exist-db
    action: command svn checkout ${existSvnUrl} ${existDir}
    when_string: ${buildSuccess.stdout} != 'BUILD SUCCESSFUL'
    
  - name: build existdb with javac in this location ${existDir}
    action: script ../../bash/buildExistdb.sh ${existDir}
    when_string: ${buildSuccess.stdout} != 'BUILD SUCCESSFUL'

    # wonky alert - these debug messages let the ln -s get created 
  - name: debug 1
    action: debug msg="1"
    
  - name: create a generic exist symbolic link
    action: file src="${existDir}" dest="${existLn}" state=link
    ignore_errors: True
    
    # wonky alert - these debug messages let the ln -s get created 
  - name: debug 2 
    action: debug msg="2"
    
    name: get the value of $JAVA_HOME
    action: shell source /etc/profile; echo $JAVA_HOME
    register: actualJavaHome
    
  - name: echo JAVA_HOME                                                  
    action: debug msg=${actualJavaHome.stdout}                               

  - name: add EXIST_HOME to /etc/profile
    action: lineinfile backup="yes" dest="/etc/profile" insertafter="EOF" state=present line="source /home/ec2-user/ec2ExistEnv.sh" regexp="^source /home/ec2-user/ec2ExistEnv\.sh$"
     
  - name: add ec2ExistEnv.sh to ec2-user home
    action: template src=../templates/ec2ExistEnv.template dest=/home/ec2-user/ec2ExistEnv.sh mode=0555
    
  - name: source /etc/profile
    action: shell source /etc/profile
    ignore_errors: True
    
  - name: create a /etc/rc.d/rc.local file with -rwxr-xr-x file permissions (this file starts exist on reboot) 
    action: template backup=yes src=../templates/ec2ExistRclocal.template dest=/etc/rc.d/rc.local mode=0755