# test the template playbook
- hosts: targets
  vars:
    avar: some value here
    destfile: ~/somefile.txt
    templatesrcfile: ../templates/test.template 
  tasks:
  - name: remove the results of the last template substitution
    action: command rm ${destfile}
    ignore_errors: yes
  - name: do some template substitution on ${templatesrcfile} and produce ${destfile}
    action: template src=${templatesrcfile} dest=${destfile}